create table categorie (cat_id integer generated by default as identity, cat_libelle varchar(50), primary key (cat_id));

INSERT INTO categorie (CAT_LIBELLE) VALUES
('Parachute de France'),
('Combinaison'),
('Et hop');